server:
  port: 80
spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}

eureka:
  client:
    # 表示是否将自己注册进Eureka Server，默认true
    register-with-eureka: false
    # 是否从Eureka Server抓取已有的注册信息，默认为true，集群必须设置此项才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: consumer-order

ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 7000

feign:
  hystrix:
    enabled: true

logging:
  level:
    top.murphypen.springcloud.service.OrderService: debug